apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-base-app
  namespace: test-10
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: test-base-app
spec:
  destination:
    namespace: test-10  # Change this to test-10
    server: https://kubernetes.default.svc  # Kubernetes API server
  project: default
  source:
    repoURL: https://github.com/siddhant179/test2.git  # Repository containing child applications
    targetRevision: HEAD
    path: apps/  # Path to a folder containing Application manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
